inference:
  hidden_dim: 2048
  intermediate_dim: 768
  instance_name: local-test
  model_name: qwen3-30b-a3b

db:
  db_dsn: postgres://dev:dev@192.168.5.94:30603/dev
  max_conn_size: 32

weight:
  server:
    addr: http://localhost:6543
  cache:
    Fs:
      path: /home/zhangyz/cache

worker:
  id: local-dev
  listen: 0.0.0.0
  broadcast: 127.0.0.1
  ports:
    main: 51234
  device: cpu

controller:
  listen: 0.0.0.0
  broadcast: localhost
  ports:
    intra: 5001
    inter: 5002
