# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from expertkit_torch.pbpy.ek.worker.v1 import expert_pb2 as ek_dot_worker_dot_v1_dot_expert__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ek/worker/v1/expert_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComputationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Forward = channel.unary_unary(
                '/ek.worker.v1.ComputationService/Forward',
                request_serializer=ek_dot_worker_dot_v1_dot_expert__pb2.ForwardReq.SerializeToString,
                response_deserializer=ek_dot_worker_dot_v1_dot_expert__pb2.ForwardResp.FromString,
                _registered_method=True)


class ComputationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Forward(self, request, context):
        """TODO: Batch Forward
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Forward': grpc.unary_unary_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=ek_dot_worker_dot_v1_dot_expert__pb2.ForwardReq.FromString,
                    response_serializer=ek_dot_worker_dot_v1_dot_expert__pb2.ForwardResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ek.worker.v1.ComputationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ek.worker.v1.ComputationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComputationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.worker.v1.ComputationService/Forward',
            ek_dot_worker_dot_v1_dot_expert__pb2.ForwardReq.SerializeToString,
            ek_dot_worker_dot_v1_dot_expert__pb2.ForwardResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exchange = channel.stream_stream(
                '/ek.worker.v1.StateService/Exchange',
                request_serializer=ek_dot_worker_dot_v1_dot_expert__pb2.ExchangeReq.SerializeToString,
                response_deserializer=ek_dot_worker_dot_v1_dot_expert__pb2.ExchangeResp.FromString,
                _registered_method=True)


class StateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Exchange(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exchange': grpc.stream_stream_rpc_method_handler(
                    servicer.Exchange,
                    request_deserializer=ek_dot_worker_dot_v1_dot_expert__pb2.ExchangeReq.FromString,
                    response_serializer=ek_dot_worker_dot_v1_dot_expert__pb2.ExchangeResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ek.worker.v1.StateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ek.worker.v1.StateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Exchange(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ek.worker.v1.StateService/Exchange',
            ek_dot_worker_dot_v1_dot_expert__pb2.ExchangeReq.SerializeToString,
            ek_dot_worker_dot_v1_dot_expert__pb2.ExchangeResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
